/*
 * jw3b.dev v2 — concierge status model (P5 · FR-020/FR-021 completion)  ·  full-stack-integrator
 *
 * PURE. The site labelled a DEGRADED answer honestly but said nothing when things were working,
 * so a visitor could not tell whether the agent was up before asking, or whether the reply they
 * just read came from the live model or the bundled recording. Honesty that only appears on
 * failure isn't honesty, it's an error message.
 *
 * The distinction this module protects: a `/health` probe proves the WORKER is reachable and
 * its bindings exist. It does NOT prove the model will answer — only a completed exchange
 * proves that. So probe results and exchange results are separate inputs, and a probe alone
 * can never produce the word "live".
 */

export const AGENT_STATUS = Object.freeze({
  UNKNOWN: 'unknown', // nothing observed yet
  CHECKING: 'checking', // probe in flight
  OFFLINE: 'offline', // worker unreachable, or its AI bindings are absent
  READY: 'ready', // worker reachable + bindings present — but nothing answered yet
  LIVE: 'live', // PROVEN: a real model answer arrived
  RECORDED: 'recorded', // PROVEN: the last answer came from the bundled fallback
})

/**
 * Fold a `/health` probe into a status. Never returns LIVE — reachability is not an answer.
 * @param {{ok?:boolean, ai?:boolean, model?:boolean}|null} health  null = probe failed
 */
export function statusFromHealth(health) {
  if (!health || health.ok !== true) return AGENT_STATUS.OFFLINE
  // Bindings missing means the concierge can only ever serve recordings — say so up front
  // rather than letting the visitor discover it by asking.
  if (!health.ai && !health.model) return AGENT_STATUS.OFFLINE
  return AGENT_STATUS.READY
}

/** Fold a COMPLETED exchange into a status — the only source of LIVE or RECORDED. */
export function statusFromExchange(degraded) {
  return degraded ? AGENT_STATUS.RECORDED : AGENT_STATUS.LIVE
}

/**
 * How the status should read to a visitor. `proven` marks the states that came from a real
 * exchange rather than a probe, so the UI can distinguish "should work" from "did work".
 */
export function statusLabel(status) {
  switch (status) {
    case AGENT_STATUS.LIVE:
      return { text: 'Live — answering now', tone: 'verified', proven: true }
    case AGENT_STATUS.RECORDED:
      // Deliberately NOT "live agent unavailable" — the message bubble already says that, and
      // repeating it in the header is noise (and made the phrase ambiguous to assert on).
      return { text: 'Serving recorded answers', tone: 'caution', proven: true }
    case AGENT_STATUS.READY:
      return { text: 'Agent online', tone: 'verified', proven: false }
    case AGENT_STATUS.OFFLINE:
      return { text: 'Agent offline', tone: 'caution', proven: false }
    case AGENT_STATUS.CHECKING:
      return { text: 'Checking agent…', tone: 'muted', proven: false }
    default:
      return { text: 'Agent status unknown', tone: 'muted', proven: false }
  }
}

/** Per-message provenance badge. Every completed assistant reply carries one. */
export function answerProvenance(message) {
  if (!message || message.role !== 'assistant' || message.pending) return null
  return message.degraded
    ? { text: 'recorded', tone: 'caution', title: 'Bundled fallback — the live agent was unavailable' }
    : { text: 'live', tone: 'verified', title: 'Generated by the live model just now' }
}
