/*
 * jw3b.dev v2 — audit run history (ADR-P5-02 · W-5)  ·  frontend-engineer
 *
 * One tab per analysis. Each run keeps the EXACT source it analysed, so an old analysis can never
 * be read against new code — the thing a single scrolling result pane got wrong by construction.
 *
 * Every panel carries, without exception (ADR-P5-02 §5):
 *   · which checkpoint it analysed, and whether that still matches the editor (stale)
 *   · its OWN provenance — run 1 may be live and run 3 recorded; a page-level label would lie
 *   · its OWN copy of the disclaimer (FR-014 is per result set, not per page)
 *
 * The fix buttons here are filtered by `fixesFor(runFindings, draft)`, which only returns fixes
 * that still change the CURRENT draft. So a remediation this run recommended, that you have since
 * applied or edited past, simply isn't offered — rather than sitting there as a button that would
 * quietly do nothing.
 */
import { useMemo } from 'react'
import ResultTabs from './ResultTabs.jsx'
import { auditSolidity, SEVERITY_META } from '../../lib/auditHeuristics.js'
import { fixesFor } from '../../lib/auditFixes.js'
import { AUDIT_DISCLAIMER } from '../../lib/auditClient.js'
import { RUN_STATUS, runIsStale } from '../../lib/auditWorkspace.js'

function RunPanel({ run, draft, onApplyFix, onRestore }) {
  // Derived from the run's pinned source, never stored — same rule as the live panel, so a run
  // tab always re-screens to exactly what the detector said about that text.
  const findings = useMemo(() => auditSolidity(run.source).findings, [run.source])
  const fixes = useMemo(() => fixesFor(findings, draft), [findings, draft])
  // The staleness rule has ONE definition (auditWorkspace) — this used to re-derive it inline.
  const stale = runIsStale(run, draft)
  const streaming = run.status === RUN_STATUS.STREAMING

  return (
    <div className="mt-3 rounded-md border border-hairline bg-void p-3">
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-mono text-[10px] uppercase tracking-label text-content-muted">
          Analysed · {run.versionLabel}
        </span>
        <span
          title={
            streaming
              ? 'Streaming from the live model'
              : run.degraded
                ? 'Bundled fallback — the live model was unavailable'
                : 'Generated by the live model just now'
          }
          className={
            'font-mono text-[10px] uppercase tracking-label ' +
            (streaming ? 'text-content-muted' : run.degraded ? 'text-caution' : 'text-verified')
          }
        >
          {streaming ? 'streaming…' : run.degraded ? 'recorded fallback' : 'live model'}
        </span>
        {stale && (
          <span
            title="The editor has changed since this analysis ran"
            className="font-mono text-[10px] uppercase tracking-label text-caution"
          >
            stale
          </span>
        )}
        {stale && (
          <button
            type="button"
            onClick={() => onRestore(run.versionId)}
            className="ml-auto rounded-md border border-hairline px-2 py-1 font-mono text-[10px] uppercase tracking-label text-content-secondary hover:text-content-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan"
          >
            Restore this version
          </button>
        )}
      </div>

      {stale && (
        <p className="mt-2 text-xs text-caution">
          This describes <span className="font-mono">{run.versionLabel}</span>, not what&rsquo;s in the
          editor now.
        </p>
      )}

      {findings.length > 0 && (
        <ul className="mt-3 space-y-1.5">
          {findings.map((f) => {
            const meta = SEVERITY_META[f.severity]
            const fix = fixes.find((x) => x.findingId === f.id)
            return (
              <li key={`${f.id}-${f.line}`} className="flex flex-wrap items-center gap-2 text-xs">
                <span className={`h-1.5 w-1.5 rounded-full ${meta.dot}`} aria-hidden="true" />
                <span className={`font-bold ${meta.tone}`}>{meta.label}</span>
                <span className="text-content-secondary">{f.title}</span>
                <span className="text-content-muted">line {f.line}</span>
                {fix && (
                  <button
                    type="button"
                    onClick={() => onApplyFix(fix)}
                    title={`Rule-derived fix — ${fix.description}`}
                    className="rounded border border-cyan/40 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-label text-cyan hover:bg-cyan/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan"
                  >
                    Apply fix
                  </button>
                )}
              </li>
            )
          })}
        </ul>
      )}

      {run.narrative ? (
        <div className="mt-3">
          <ResultTabs source={run.narrative} streaming={streaming} label={`Run ${run.seq} analysis sections`} />
        </div>
      ) : (
        <p className="mt-3 text-xs text-content-muted">
          {streaming ? 'Waiting for the model…' : 'No narrative arrived for this run — the findings above are still real.'}
        </p>
      )}

      {/* FR-014 / BR-10: the disclaimer belongs to the RESULT SET, so it repeats per run. */}
      <p className="mt-3 border-t border-hairline pt-2 text-[11px] text-content-muted">{AUDIT_DISCLAIMER}</p>
    </div>
  )
}

export default function RunTabs({ runs, selectedRun, onSelect, draft, onApplyFix, onRestore }) {
  if (!runs.length) return null

  const activeId = selectedRun?.id ?? runs[runs.length - 1].id

  const onKeyDown = (e) => {
    const i = runs.findIndex((r) => r.id === activeId)
    if (e.key === 'ArrowRight') onSelect(runs[(i + 1) % runs.length].id)
    if (e.key === 'ArrowLeft') onSelect(runs[(i - 1 + runs.length) % runs.length].id)
  }

  return (
    <section aria-labelledby="run-history-title" className="rounded-lg border border-cyan/25 bg-panel p-4">
      <p className="font-mono text-[10px] uppercase tracking-label text-content-muted">
        <span className="text-cyan">4</span> · AI analyses ({runs.length})
      </p>
      <h4 id="run-history-title" className="mt-0.5 text-[11px] text-content-muted">
        Every analysis you&rsquo;ve run, each pinned to the version it read. Opening one costs nothing.
      </h4>

      <div role="tablist" aria-label="AI analyses" onKeyDown={onKeyDown} className="mt-3 flex flex-wrap gap-1.5">
        {runs.map((r) => {
          const isActive = r.id === activeId
          return (
            <button
              key={r.id}
              role="tab"
              type="button"
              id={`run-tab-${r.id}`}
              aria-selected={isActive}
              aria-controls={`run-panel-${r.id}`}
              tabIndex={isActive ? 0 : -1}
              onClick={() => onSelect(r.id)}
              title={`Analysed ${r.versionLabel}`}
              className={
                'max-w-[14rem] truncate rounded-md border px-2.5 py-1 font-mono text-[10px] uppercase tracking-label motion-safe:transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan ' +
                (isActive ? 'border-cyan/50 bg-cyan/10 text-cyan' : 'border-hairline text-content-muted hover:text-content-secondary')
              }
            >
              Run {r.seq} · {r.versionLabel}
              {r.status === RUN_STATUS.STREAMING && <span aria-hidden="true"> ▍</span>}
            </button>
          )
        })}
      </div>

      {runs.map((r) => (
        <div key={r.id} role="tabpanel" id={`run-panel-${r.id}`} aria-labelledby={`run-tab-${r.id}`} hidden={r.id !== activeId}>
          {r.id === activeId && <RunPanel run={r} draft={draft} onApplyFix={onApplyFix} onRestore={onRestore} />}
        </div>
      ))}
    </section>
  )
}
